services:

  inception-nginx:
    build:
      context: requirements/nginx/.
      dockerfile: Dockerfile
    image: "inception-nginx:webserv"
    container_name: inception-nginx
    restart: always
    depends_on:
      - inception-mariadb
      - inception-wordpress
    ports:
      - "443:443"
    volumes:
      - /home/cassie/data/wordpress:/var/www/html
    networks:
      - inception-network

  inception-wordpress:
    build:
      context: requirements/wordpress/.
      dockerfile: Dockerfile
    image: "inception-wordpress:website"
    container_name: inception-wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - inception-mariadb
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - /home/cassie/data/wordpress:/var/www/html
    networks:
      - inception-network

  inception-mariadb:
    build:
      context: requirements/mariadb/.
      dockerfile: Dockerfile
    image: "inception-mariadb:database"
    container_name: inception-mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - /home/cassie/data/mariadb:/var/lib/mysql
    networks:
      - inception-network

  inception-adminer:
    build:
      context: bonus/adminer/.
      dockerfile: Dockerfile
    image: "inception-adminer:adminer"
    container_name: inception-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - inception-mariadb
    networks:
      - inception-network
    
networks:
  inception-network:

