services:
  nginx:
    build:
      context: requirements/nginx/.
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "80:80"
    volumes:
      - /home/goudoulf/data/wordpress:/var/www/html
    networks:
      - inception-network
  wordpress:
    build:
      context: requirements/wordpress/.
      dockerfile: Dockerfile
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - /home/goudoulf/data/wordpress:/var/www/html
    networks:
      - inception-network
  mariadb:
    build:
      context: requirements/mariadb/.
      dockerfile: Dockerfile
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: wppassword
    volumes:
      - /home/goudoulf/data/mariadb:/var/lib/mysql
    networks:
      - inception-network

networks:
  inception-network:

