services:

  nginx:
    build:
      context: requirements/nginx/.
      dockerfile: Dockerfile
    image: "inception-nginx:webserv"
    container_name: nginx
    restart: always
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/cassie/data/wordpress:/var/www/html
    networks:
      - inception-network

  wordpress:
    build:
      context: requirements/wordpress/.
      dockerfile: Dockerfile
    image: "inception-wordpress:website"
    container_name: wp-php
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - /home/cassie/data/wordpress:/var/www/html
    networks:
      - inception-network

  mariadb:
    build:
      context: requirements/mariadb/.
      dockerfile: Dockerfile
    image: "inception-mariadb:database"
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - /home/cassie/data/mariadb:/var/lib/mysql
    networks:
      - inception-network

  adminer:
    build:
      context: requirements/bonus/adminer/.
      dockerfile: Dockerfile
    image: "inception-adminer:adminer"
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception-network

networks:
  inception-network:

